name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite/setup-node
      - run: pnpm run lint
      - run: pnpm run fmt
      - run: pnpm run build
